events {}

http {
    upstream apimeter {
        server apimeter:8080;
    }

    upstream orderapi {
        server orderapi:8080;
    }

    server {
        listen 80;

        location /meter/ {
            rewrite ^/meter/(.*) /$1 break;
            proxy_pass http://apimeter;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /order/ {
            rewrite ^/order/(.*) /$1 break;
            proxy_pass http://orderapi;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}