apiVersion: v1
kind: Secret
metadata:
  name: apimeter-secret
  namespace: microservices
type: Opaque
stringData:
  connection-string: "Host=apimeter-db-service;Port=5432;Database=apimeter_db;Username=postgres;Password=password"