apiVersion: apps/v1
kind: Deployment
metadata:
  name: apimeter-db-deployment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apimeter-db
  template:
    metadata:
      labels:
        app: apimeter-db
    spec:
      containers:
        - name: apimeter-db
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "apimeter_db"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: apimeter-db-pvc