apiVersion: v1
kind: Secret
metadata:
  name: apimeter-db-secret
  namespace: microservices
type: Opaque 
stringData:
    connection-string: "Host=apimeter-db;Port=5432;Database=apimeter_db;Username=postgres;Password=password"

