apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
  namespace: microservices
type: Opaque
stringData:
    connection-string: "Host=order-db;Port=5432;Database=order_db;Username=postgres;Password=password"